# Generated by Django 4.2 on 2025-02-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causes_Of_Obstacles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obstacle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry_Type', models.CharField(max_length=20)),
                ('Sector_Type', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Wilaya', models.CharField(choices=[('1', 'Adrar'), ('2', 'Chlef'), ('3', 'Laghouat'), ('4', 'Oum El Bouaghi'), ('5', 'Batna'), ('6', 'Béjaïa'), ('7', 'Biskra'), ('8', 'Béchar'), ('9', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', 'Timimoun'), ('50', 'Bordj Badji Mokhtar'), ('51', 'Ouled Djellal'), ('52', 'Béni Abbès'), ('53', 'In Salah'), ('54', 'In Guezzam'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', "El M'Ghair"), ('58', 'El Meniaa')], max_length=100)),
                ('Commune', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('Name_Institution', models.CharField(max_length=250)),
                ('Activity', models.CharField(max_length=250)),
                ('Institution_Establishment_Year', models.IntegerField()),
                ('Start_Activity_Year', models.IntegerField()),
                ('Commercial_Registration_Number', models.CharField(max_length=30)),
                ('Tax_Identification_Number', models.CharField(max_length=30)),
                ('Legal_Form', models.CharField(choices=[('1', 'SNC'), ('2', 'SCS'), ('3', 'ARTISANT'), ('4', 'AUTRES')], max_length=20)),
                ('Legal_Status', models.CharField(choices=[('1', 'Publique'), ('2', 'Privé'), ('3', 'Mixte(nationale/étrangère)')], max_length=30)),
                ('Number_Direct_Jobs', models.IntegerField()),
                ('Number_Indirect_Jobs', models.IntegerField()),
                ('Total_Covered_Storage_Area', models.IntegerField()),
                ('Total_Uncovered_Storage_Area', models.IntegerField()),
                ('Origin_Ownership', models.CharField(choices=[('1', 'عقد امتياز '), ('2', 'كراء'), ('3', 'خاصة')], max_length=20)),
                ('Shortage_In_Raw_Material', models.BooleanField(default=False)),
                ('Benefit_From_Public_Agencies_Support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raw_Material', models.CharField(max_length=150)),
                ('Monthly_Consumption', models.CharField(max_length=30)),
                ('Source', models.CharField(choices=[('1', 'مستورد'), ('2', 'محلي')], max_length=20)),
                ('Source_Country', models.CharField(default='Algeria', max_length=100)),
                ('Is_Scarce', models.BooleanField(default=False)),
                ('Quantities_Required_To_Reach_Maximum_Production_Capacity_Monthly', models.CharField(max_length=100)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='gtexForm.company')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAgenciesAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Agencies_And_Services', models.CharField(max_length=150)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_agencies_services', to='gtexForm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Obstacles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('More_Obstacles', models.TextField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_obstacles', to='gtexForm.company')),
                ('Reasons_For_Not_Achieving_Max_Capacity', models.ManyToManyField(to='gtexForm.causes_of_obstacles')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Production_Capacity_Monthly', models.CharField(max_length=30)),
                ('Actual_Production_Volume', models.CharField(max_length=30)),
                ('Target_Market', models.CharField(max_length=150)),
                ('Target_Audience', models.CharField(max_length=50)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gtexForm.company')),
            ],
        ),
    ]
