# Generated by Django 4.2 on 2025-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtexForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Legal_Form',
            field=models.CharField(choices=[('1', 'SPA'), ('2', 'SARL'), ('3', 'EURL'), ('4', 'SNC'), ('5', 'SCS'), ('6', 'ARTISANT'), ('7', 'AUTRES')], max_length=20),
        ),
        migrations.AlterField(
            model_name='production_obstacles',
            name='More_Obstacles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='production_obstacles',
            name='Reasons_For_Not_Achieving_Max_Capacity',
            field=models.ManyToManyField(blank=True, to='gtexForm.causes_of_obstacles'),
        ),
        migrations.AlterField(
            model_name='publicagenciesandservices',
            name='List_Agencies_And_Services',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
