# Generated by Django 4.2 on 2025-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtexForm', '0002_alter_company_legal_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Actual_Production_Unit',
            field=models.CharField(default='liter', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Actual_Production_Volume',
            field=models.CharField(max_length=50),
        ),
    ]
